import networkx as nx
from phart import ASCIIRenderer, NodeStyle
G = nx.DiGraph()
G.add_node('NocGarnetNetwork')
G.add_node('NocGarnetRouter(NOC_NPS_VNOC_X3Y0,id=1)')
G.add_node('NocGarnetRouter(NOC_NPS_VNOC_X3Y1,id=0)')
G.add_node('NocInterface(M00_AXIS_nsu)')
G.add_node('NocInterface(S00_AXIS_nmu)')
G.add_node('cpu[0] AxisRandomTrafficGenerator')
G.add_node('cpu[1] AxisSinkNode')
G.add_node('ext_links[0] NocGarnetExtLink(id=0)')
G.add_node('ext_links[1] NocGarnetExtLink(id=2)')
G.add_node('int_links[0] NocGarnetIntLink(id=1)')
G.add_node('netifs[0] sNocMasterUnit(id=0)')
G.add_node('netifs[1] sNocSlaveUnit(id=1)')
G.add_edge('NocGarnetNetwork', 'netifs[0] sNocMasterUnit(id=0)', label='netifs')
G.add_edge('netifs[0] sNocMasterUnit(id=0)', 'NocGarnetNetwork', label='netifs')
G.add_edge('NocGarnetNetwork', 'netifs[1] sNocSlaveUnit(id=1)', label='netifs')
G.add_edge('netifs[1] sNocSlaveUnit(id=1)', 'NocGarnetNetwork', label='netifs')
G.add_edge('NocGarnetRouter(NOC_NPS_VNOC_X3Y0,id=1)', 'ext_links[1] NocGarnetExtLink(id=2)', label='int_node')
G.add_edge('ext_links[1] NocGarnetExtLink(id=2)', 'NocGarnetRouter(NOC_NPS_VNOC_X3Y0,id=1)', label='int_node')
G.add_edge('NocGarnetRouter(NOC_NPS_VNOC_X3Y0,id=1)', 'int_links[0] NocGarnetIntLink(id=1)', label='dst_in:port1_in')
G.add_edge('int_links[0] NocGarnetIntLink(id=1)', 'NocGarnetRouter(NOC_NPS_VNOC_X3Y0,id=1)', label='dst_in:port1_in')
G.add_edge('NocGarnetRouter(NOC_NPS_VNOC_X3Y1,id=0)', 'ext_links[0] NocGarnetExtLink(id=0)', label='int_node')
G.add_edge('ext_links[0] NocGarnetExtLink(id=0)', 'NocGarnetRouter(NOC_NPS_VNOC_X3Y1,id=0)', label='int_node')
G.add_edge('NocGarnetRouter(NOC_NPS_VNOC_X3Y1,id=0)', 'int_links[0] NocGarnetIntLink(id=1)', label='src_out:port1_out')
G.add_edge('int_links[0] NocGarnetIntLink(id=1)', 'NocGarnetRouter(NOC_NPS_VNOC_X3Y1,id=0)', label='src_out:port1_out')
G.add_edge('NocInterface(M00_AXIS_nsu)', 'cpu[1] AxisSinkNode', label='endpoint:M00_AXIS_nsu')
G.add_edge('cpu[1] AxisSinkNode', 'NocInterface(M00_AXIS_nsu)', label='endpoint:M00_AXIS_nsu')
G.add_edge('NocInterface(M00_AXIS_nsu)', 'netifs[1] sNocSlaveUnit(id=1)', label='NMU/NSU')
G.add_edge('netifs[1] sNocSlaveUnit(id=1)', 'NocInterface(M00_AXIS_nsu)', label='NMU/NSU')
G.add_edge('NocInterface(S00_AXIS_nmu)', 'cpu[0] AxisRandomTrafficGenerator', label='endpoint:S00_AXIS_nmu')
G.add_edge('cpu[0] AxisRandomTrafficGenerator', 'NocInterface(S00_AXIS_nmu)', label='endpoint:S00_AXIS_nmu')
G.add_edge('NocInterface(S00_AXIS_nmu)', 'netifs[0] sNocMasterUnit(id=0)', label='NMU/NSU')
G.add_edge('netifs[0] sNocMasterUnit(id=0)', 'NocInterface(S00_AXIS_nmu)', label='NMU/NSU')
G.add_edge('ext_links[0] NocGarnetExtLink(id=0)', 'netifs[0] sNocMasterUnit(id=0)', label='ext_link')
G.add_edge('netifs[0] sNocMasterUnit(id=0)', 'ext_links[0] NocGarnetExtLink(id=0)', label='ext_link')
G.add_edge('ext_links[1] NocGarnetExtLink(id=2)', 'netifs[1] sNocSlaveUnit(id=1)', label='ext_link')
G.add_edge('netifs[1] sNocSlaveUnit(id=1)', 'ext_links[1] NocGarnetExtLink(id=2)', label='ext_link')
renderer = ASCIIRenderer(G, node_style=NodeStyle.SQUARE)
print(renderer.render())
