/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   /home/mlanz2/gem5/src/mem/slicc/symbols/Type.py:666
 */

 #include <iostream>
 #include <memory>

 #include "noc/core/network/NocMemoryMsg.hh"
 #include "noc/core/network/NocSystem.hh"

 namespace gem5
 {

 namespace noc
 {


 /** \brief Print the state of this object */
 void
 NocMemoryMsg::print(std::ostream& out) const
 {
     out << "[MemoryMsg: ";
    //  out << "addr = " << gem5::ruby::printAddress(m_addr, block_size_bits) << " ";
    //  out << "Type = " << m_Type << " ";
    //  out << "Sender = " << m_Sender << " ";
    //  out << "OriginalRequestorMachId = " << m_OriginalRequestorMachId << " ";
    //  out << "DataBlk = " << m_DataBlk << " ";
     out << "MessageSize = " << m_MessageSize << " ";
    //  out << "Len = " << m_Len << " ";
    //  out << "Prefetch = " << m_Prefetch << " ";
    //  out << "ReadX = " << m_ReadX << " ";
    //  out << "Acks = " << m_Acks << " ";
    //  out << "isGLCSet = " << m_isGLCSet << " ";
    //  out << "isSLCSet = " << m_isSLCSet << " ";
     out << "]\n";
 }
//  bool
//  NocMemoryMsg::functionalRead(Packet* param_pkt)
//  {
//      if (((m_MessageSize == gem5::ruby::MessageSizeType_Response_Data) || (m_MessageSize == gem5::ruby::MessageSizeType_Writeback_Data))) {
//          return (testAndRead(m_addr, m_DataBlk, param_pkt));
//      }
//      return (false);

//  }
//  bool
//  NocMemoryMsg::functionalRead(Packet* param_pkt, gem5::ruby::WriteMask& param_mask)
//  {
//      if (((m_MessageSize == gem5::ruby::MessageSizeType_Response_Data) || (m_MessageSize == gem5::ruby::MessageSizeType_Writeback_Data))) {
//          gem5::ruby::WriteMask read_mask;
//          ((read_mask).setBlockSize(((param_mask).getBlockSize())));
//          ((read_mask).setMask((gem5::ruby::addressOffset(m_addr, (gem5::ruby::makeLineAddress(m_addr, ((param_mask).getBlockSize()))))), m_Len, (true)));
//              if ((m_MessageSize != gem5::ruby::MessageSizeType_Writeback_Data)) {
//                  ((read_mask).setInvertedMask(param_mask));
//              }
//                  if (((read_mask).isEmpty())) {
//                      return (false);
//                  } else {
//                          if ((testAndReadMask(m_addr, m_DataBlk, read_mask, param_pkt))) {
//                              ((param_mask).orMask(read_mask));
//                              return (true);
//                          }
//                      }
//                  }
//                  return (false);

//  }
//  bool
//  NocMemoryMsg::functionalWrite(Packet* param_pkt)
//  {
//  return (testAndWrite(m_addr, m_DataBlk, param_pkt));

//  }

std::array<uint8_t, 16> NocMemoryMsg::getFlitData(uint8_t flit_id){

    std::array<uint8_t, 16> flit_data;
    uint8_t beat_size = (1 << m_beat_size);


    auto *p = std::get_if<aximmPayload>(&m_pload);
    if(!p) panic("NocMemoryMsg::getFlitData expected NocMemoryMsg payload");

    if (beat_size < 16){
        uint8_t beats_per_flit = 16/beat_size;
        uint8_t start_beat_idx = flit_id*beats_per_flit;
        uint8_t end_beat_idx = start_beat_idx + beats_per_flit;


        for (uint8_t i = start_beat_idx; i<end_beat_idx; i++){
            std::copy((*p)[i].data.begin(), (*p)[i].data.begin() + beat_size, flit_data.begin()+(i-start_beat_idx)*beat_size);
            // std::copy(m_pload[i].data.begin(), m_pload[i].data.end(), flit_data.begin()+(i-start_beat_idx)*beat_size);
        }
    } else if (beat_size == 16){
        // flit_id corresponds to beat id, just copy the 16 bytes over (only first 16B of m_pload.data are valid)
        std::copy((*p)[flit_id].data.begin(), (*p)[flit_id].data.begin() + 16, flit_data.begin());
    } else {
        uint8_t flits_per_beat = beat_size/16;
        uint8_t beat_idx = (flit_id*16)/beat_size;

        // flit_id % flits_per_beat gives id of section within this current beat that the flit belongs to
        // so if 64B beats, flit 4 corresponds to id 0 of beat_idx 1, flit 5 to id 1
        // flit 0 to id 0 of beat_idx 0
        std::copy((*p)[beat_idx].data.begin()+((flit_id%flits_per_beat)*16),
                    (*p)[beat_idx].data.begin()+((flit_id%flits_per_beat)*16)+16,
                    flit_data.begin());
    }

    return flit_data;
}


 } // namespace noc
 } // namespace gem5
