/**
* DO NOT EDIT THIS FILE!
* File automatically generated by
*   /home/mlanz2/gem5/src/mem/slicc/symbols/Type.py:585
*/
#ifndef __NocMemoryMsg_HH__
#define __NocMemoryMsg_HH__

#include <iostream>
#include <cstring>
#include <vector>

#include "mem/ruby/slicc_interface/RubySlicc_Util.hh"

#include "mem/ruby/protocol/MemoryRequestType.hh"
#include "mem/ruby/protocol/MachineID.hh"
#include "mem/ruby/protocol/MachineID.hh"
#include "mem/ruby/protocol/DataBlock.hh"
#include "mem/ruby/protocol/MessageSizeType.hh"
#include "mem/ruby/protocol/PrefetchBit.hh"
#include "noc/lib/network/NocMessage.hh"
#include "noc/lib/axi/AXITypes.hh"
namespace gem5
{

namespace noc
{

class NocSystem;


class NocMemoryMsg :  public NocMessage
{

    public:
    NocMemoryMsg(Tick curTime,
                NocSystem* ns,
                const AxiMsgSizeType& local_MessageSize,
                MessagePayload payload,
                aximmPayload pload = {})
                : NocMessage(curTime, ns),
                m_MessageSize(local_MessageSize),
                m_payload(std::move(payload)),
                m_pload(std::move(pload)),
                m_end_beat_idx(0),
                m_current_beat_idx(0)
    {
        setNocSystem(ns);

        // our current routing doesn't make use of NocNetDest type
        // m_Destination = NocNetDest(ns);
        // gem5::ruby::Set set(4);
        // set.add(1);

        // m_Destination.setNocSystem(ns); //resizes NocNetDest which will clear out data, do this before setting anything
        // m_Destination.setNetDest(gem5::ruby::MachineType::MachineType_L1Cache, set);

        m_num_flits = 0;


    }

    //keep copy of og constructor for use in AbstractController.cc
    NocMemoryMsg(Tick curTime, int blockSize, NocSystem* ns) : NocMessage(curTime, ns)
    {
        setNocSystem(ns);
        m_MessageSize = gem5::noc::AxiMsgSizeType::DEFAULT;
        // default value of MessageSizeType
    }

    NocMemoryMsg(const NocMemoryMsg&) = default;
    NocMemoryMsg
    &operator=(const NocMemoryMsg&) = default;

    MsgPtr
    clone() const
    {
         return std::shared_ptr<NocMessage>(new NocMemoryMsg(*this));
    }
    void setNocSystem(NocSystem *noc_system)
    {
        m_noc_system = noc_system;
    }
    NocSystem*
    getNocSystem()
    {
        return m_noc_system;
    }
    const gem5::noc::AxiMsgSizeType&
    getMessageSize() const
    {
        return m_MessageSize;
    }
    gem5::noc::AxiMsgSizeType&
    getMessageSize()
    {
        return m_MessageSize;
    }
    void
    setMessageSize(const gem5::noc::AxiMsgSizeType& local_MessageSize)
    {
        m_MessageSize = local_MessageSize;
    }

    void print(std::ostream& out) const;
    // for ruby, these destination functions done in protocol (build/NULL/mem/ruby/protocol/MI_example for ex)
    // but do here instead
    void
    setDestination(const NocNetDest& local_Destination)
    {
        m_Destination = local_Destination;
    }
    NocNetDest&
    getDestination()
    {
        return m_Destination;
    }

    MessagePayload
    getPayload() const
    {
        return m_payload;
    }

    Payload getData() const {
        return m_pload;
    }

    void
    setData(Payload payload){
        if(!std::holds_alternative<aximmPayload>(payload))
            panic("NocMemoryMsg::setData: expected aximmPayload");
        m_pload = payload;
    }

   void appendData(aximmRWData beat) {
        auto *p = std::get_if<aximmPayload> (&m_pload);
        if(!p)
            panic("NocMemoryMsg::appendData called on non-aximmPayload");
        (*p)[m_end_beat_idx] = beat;
        ++m_end_beat_idx;
    }

    void setBeatSize(uint8_t beat_size){
        m_beat_size = beat_size;
    }
    uint8_t getBeatSize() const{
        return m_beat_size;
    }

    void setBurstLen(uint8_t burst_len){
        m_burst_len = burst_len;
    }
    uint8_t getBurstLen() const { return m_burst_len; }

    std::array<uint8_t, 16> getFlitData(uint8_t flit_id);

    uint8_t getRespAXIID (){
        auto *p = std::get_if<aximmPayload>(&m_pload);
        if(!p)
            panic("NocMemoryMsg::getRespAXIID on non-aximmPayload");
        return (*p)[0].id;
    }

    void setPayload(MessagePayload payload)
    {
        m_payload = payload;
    }

    void setNumFlits(uint8_t num_flits)
    {
        m_num_flits = num_flits;
    }
    uint8_t getNumFlits() const
    {
        return m_num_flits;
    }


    garnet::WriteTag getWriteTag() const{
        return m_writeTag;
    }
    void setWriteTag(garnet::WriteTag tag){
        m_writeTag = tag;
    }

    uint8_t getRROBTag(uint8_t idx) const{
        return m_rrob_tags[idx];
    }
    void setRROBTag(uint8_t idx, uint8_t id){
        m_rrob_tags[idx] = id;
    }

    uint8_t getAxiRROBTag() const{
        return m_axi_rrob_tag;
    }
    void setAxiRROBTag(uint8_t id){
        m_axi_rrob_tag = id;
    }
    uint8_t getRROBBeatID() const{
        return m_axi_beat_id;
    }
    void setRROBBeatID(uint8_t id){
        m_axi_beat_id = id;
    }
    uint8_t getEndBeatIdx() const{
        return m_end_beat_idx;
    }
    void setEndBeatIdx(uint8_t idx) { m_end_beat_idx = idx; }
    void setCurrentBeatIdx(uint8_t idx) { m_current_beat_idx = idx; }
    uint8_t getCurrentBeatIdx() const { return m_current_beat_idx; }
    uint8_t getStartBeatIdx(){
        uint8_t ret = m_current_beat_idx;
        ++m_current_beat_idx;
        return ret;
    }

    void setSourceNiID(int id){
        m_src_ni_id = id;
    }
    int getSourceNiID() const{
        return m_src_ni_id;
    }

    void setDestNiID(int id) { m_dest_ni_id = id; }
    int getDestNiID() const { return m_dest_ni_id; }

    /**
     * Per-network-packet debug ids for AXI-MM (mirrors NocStreamMsg axisPayload::debugIds).
     * Optional; populated by AXIMM packetization when a probe assigns ids upstream.
     */
    void setNetworkProbeDebugIds(std::vector<int32_t> ids)
    {
        m_net_probe_dbg_ids = std::move(ids);
    }
    const std::vector<int32_t>& getNetworkProbeDebugIds() const
    {
        return m_net_probe_dbg_ids;
    }

    uint8_t getBeatID() const { return m_axi_beat_id; }
    void setBeatID(uint8_t id) { m_axi_beat_id = id; }

    std::array<uint8_t, 8> getRrobTags() const
    {
        std::array<uint8_t, 8> out{};
        std::memcpy(out.data(), m_rrob_tags, sizeof(m_rrob_tags));
        return out;
    }
    void setRrobTags(const std::array<uint8_t, 8> &tags)
    {
        std::memcpy(m_rrob_tags, tags.data(), sizeof(m_rrob_tags));
    }

    void setOriginalReadBytes(uint32_t bytes)
    {
        m_original_read_bytes = bytes;
    }
    uint32_t getOriginalReadBytes() const
    {
        return m_original_read_bytes;
    }
    bool hasOriginalReadBytes() const
    {
        return m_original_read_bytes > 0;
    }
    void setFinalReadChunk(bool is_final)
    {
        m_final_read_chunk = is_final;
    }
    bool isFinalReadChunk() const
    {
        return m_final_read_chunk;
    }

    void resizeRequest(uint8_t newSize){
        aximmRWAddr payload_copy;

        if(aximmRWAddr* p = std::get_if<aximmRWAddr>(&m_payload)){
            payload_copy = *p;
        } else {
            panic("trying to call NocMemoryMsg::resizeRequest on a non-request payload");
        }

        payload_copy.len = (payload_copy.getTotalByteSize() / (1<<newSize)) - 1;
        payload_copy.size = newSize;

        m_payload = payload_copy;
    }

    static void cloneRROBTags(const MsgPtr& src, const MsgPtr& dst) {
        if (!src || !dst) {
            throw std::invalid_argument("Null MsgPtr passed to cloneRROBTags");
        }

        auto src_mem = std::dynamic_pointer_cast<NocMemoryMsg>(src);
        auto dst_mem = std::dynamic_pointer_cast<NocMemoryMsg>(dst);

        if (!src_mem || !dst_mem) {
            throw std::invalid_argument("MsgPtr is not a NocMemoryMsg");
        }

        std::memcpy(dst_mem->m_rrob_tags, src_mem->m_rrob_tags, sizeof(src_mem->m_rrob_tags));
    }

    //private:
    NocNetDest m_Destination;
    gem5::noc::AxiMsgSizeType m_MessageSize;
    //  bool functionalRead(Packet* param_pkt);
    //  bool functionalRead(Packet* param_pkt, gem5::ruby::WriteMask& param_mask);
    //  bool functionalWrite(Packet* param_pkt);

    private:
        MessagePayload m_payload; //<- r/w request or w resp
        Payload m_pload; //<- what will actually house r/w data
        uint8_t m_beat_size; // beat size and burst len of the req/resp to/from slave
        uint8_t m_burst_len;

        NocSystem* m_noc_system;

        uint8_t m_num_flits; // number of flits used to transmit this message

        garnet::WriteTag m_writeTag; // used to track write requests

        // for NPP read request, need to be able to save up to 8 tags for each possible RROB entry
        uint8_t m_rrob_tags[8];

        // for AXI read response, once tile controller dequeues, the NMU callback needs to know
        // which RROB entry and beat it was so it can be marked as read and the entire entry can later be freed
        uint8_t m_axi_rrob_tag;
        uint8_t m_axi_beat_id;
        uint8_t m_end_beat_idx;
        uint8_t m_current_beat_idx;

        int m_dest_ni_id;
        int m_src_ni_id;

        /** See setNetworkProbeDebugIds */
        std::vector<int32_t> m_net_probe_dbg_ids;

        uint32_t m_original_read_bytes = 0;
        bool m_final_read_chunk = false;
};

inline ::std::ostream&
operator<<(::std::ostream& out, const NocMemoryMsg& obj)
{
    obj.print(out);
    out << ::std::flush;
    return out;
}

} // namespace noc
} // namespace gem5

#endif // __MemoryMsg_HH__
