/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   /home/mlanz2/gem5/src/mem/slicc/symbols/Type.py:666
 */

 #include <iostream>
 #include <memory>

 #include "noc/core/network/NocStreamMsg.hh"
 #include "noc/core/network/NocSystem.hh"

 namespace gem5
 {

 namespace noc
 {


 /** \brief Print the state of this object */
 void
 NocStreamMsg::print(std::ostream& out) const
 {
     out << "[StreamMsg: ";
    //  out << "addr = " << gem5::ruby::printAddress(m_addr, block_size_bits) << " ";
    //  out << "Type = " << m_Type << " ";
    //  out << "Sender = " << m_Sender << " ";
    //  out << "OriginalRequestorMachId = " << m_OriginalRequestorMachId << " ";
    //  out << "DataBlk = " << m_DataBlk << " ";
     out << "MessageSize = " << m_MessageSize << " ";
    //  out << "Len = " << m_Len << " ";
    //  out << "Prefetch = " << m_Prefetch << " ";
    //  out << "ReadX = " << m_ReadX << " ";
    //  out << "Acks = " << m_Acks << " ";
    //  out << "isGLCSet = " << m_isGLCSet << " ";
    //  out << "isSLCSet = " << m_isSLCSet << " ";
     out << "]\n";
 }
//  bool
//  NocMemoryMsg::functionalRead(Packet* param_pkt)
//  {
//      if (((m_MessageSize == gem5::ruby::MessageSizeType_Response_Data) || (m_MessageSize == gem5::ruby::MessageSizeType_Writeback_Data))) {
//          return (testAndRead(m_addr, m_DataBlk, param_pkt));
//      }
//      return (false);

//  }
//  bool
//  NocMemoryMsg::functionalRead(Packet* param_pkt, gem5::ruby::WriteMask& param_mask)
//  {
//      if (((m_MessageSize == gem5::ruby::MessageSizeType_Response_Data) || (m_MessageSize == gem5::ruby::MessageSizeType_Writeback_Data))) {
//          gem5::ruby::WriteMask read_mask;
//          ((read_mask).setBlockSize(((param_mask).getBlockSize())));
//          ((read_mask).setMask((gem5::ruby::addressOffset(m_addr, (gem5::ruby::makeLineAddress(m_addr, ((param_mask).getBlockSize()))))), m_Len, (true)));
//              if ((m_MessageSize != gem5::ruby::MessageSizeType_Writeback_Data)) {
//                  ((read_mask).setInvertedMask(param_mask));
//              }
//                  if (((read_mask).isEmpty())) {
//                      return (false);
//                  } else {
//                          if ((testAndReadMask(m_addr, m_DataBlk, read_mask, param_pkt))) {
//                              ((param_mask).orMask(read_mask));
//                              return (true);
//                          }
//                      }
//                  }
//                  return (false);

//  }
//  bool
//  NocMemoryMsg::functionalWrite(Packet* param_pkt)
//  {
//  return (testAndWrite(m_addr, m_DataBlk, param_pkt));

//  }

std::array<uint8_t, 16> NocStreamMsg::getFlitData(uint8_t flit_id){

    std::array<uint8_t, 16> flit_data; // 128 bits of data
    // uint8_t beat_size = m_beat_size; // note this is in bytes. up to how many bytes each axisData in the payload can hold

    auto *p = std::get_if<axisPayload>(&m_pload);
    if(!p) panic("NocStreamMsg::getFlitData expected NocStreamMsg payload");

    // iterate through p->beats and find the flit_id*128/8th byte of data
    flit_data.fill(0);    // zero-pad in case fewer than 16 bytes remain

    const int flit_start = flit_id * 16;
    const int flit_end   = flit_start + 16;

    int valid_pos = 0;    // running count of valid bytes encountered across all beats
    int out_idx = 0;      // index into flit_data

    // Traverse beats and within each beat traverse all lanes, selecting only bytes enabled by tkeep.
    for (const auto &beat : p->beats) {
        const auto &data = beat.tdata;
        const int lanes = static_cast<int>(data.size());
        for (int lane = 0; lane < lanes; ++lane) {
            if (beat.tkeep & (1ULL << lane)) {
                if (valid_pos >= flit_start && valid_pos < flit_end && out_idx < 16) {
                    flit_data[out_idx++] = data[lane];
                }
                ++valid_pos;
                if (valid_pos >= flit_end && out_idx >= 16) {
                    // We've filled the flit; early exit
                    return flit_data;
                }
            }
        }
    }

    return flit_data;
}

bool NocStreamMsg::containsLast() {
    auto *p = std::get_if<axisPayload>(&m_pload);
    if(!p) panic("NocStreamMsg::containsLast expected NocStreamMsg payload");
    return p->last;
}


 } // namespace noc
 } // namespace gem5
